services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: english_tma_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/alembic:/app/alembic
      - ./backend/alembic.ini:/app/alembic.ini
    environment:
      BOT_TOKEN: ${BOT_TOKEN:-dummy_token}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-english_tma}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: english_tma_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: english_tma_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-english_tma}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: english_tma_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://frontend:5173
    depends_on:
      - frontend
        
volumes:
  postgres_data: